name: scipaper
channels:
  - defaults
  - conda-forge
dependencies:
  - fastapi
  - gunicorn
  - ipython
  - jupyter
  - keyring
  - pandas
  - python<3.8
  - requests
  - sqlalchemy
  - sqlite
  - uvicorn
