name: scipaper
channels:
  - defaults
  - conda-forge
dependencies:
  - dill
  - fastapi
  - ipython
  - joblib
  - jupyter
  - keyring
  - pandas
  - python<3.8
  - requests
  - scikit-learn
  - sqlalchemy
  - sqlite
  - uvicorn
